/*
 * Copyright (C) 2017 Mohamad Saada
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package Logi.GSeries.Keyboard;

/**
 *
 * @author Mohamad Saada
 */
public class KeyboardLayoutJDialog extends javax.swing.JDialog {

    String selectedKeyboardLayout = "US_QWERTY";

    /**
     * Creates new form KeyboardLayoutJDialog
     */
    public KeyboardLayoutJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelLayout = new javax.swing.JLabel();
        jComboBoxKeyboardLayout = new javax.swing.JComboBox<>();
        jButtonSaveLayout = new javax.swing.JButton();

        setTitle("K. Layout");
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(200, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLayout.setText("Layout:");
        jPanel1.add(jLabelLayout, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 13, -1, -1));

        jComboBoxKeyboardLayout.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "US_QWERTY", "UK_QWERTY" }));
        jPanel1.add(jComboBoxKeyboardLayout, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 10, -1, -1));

        jButtonSaveLayout.setText("Save");
        jButtonSaveLayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveLayoutActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSaveLayout, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveLayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveLayoutActionPerformed
        selectedKeyboardLayout = jComboBoxKeyboardLayout.getSelectedItem().toString();
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSaveLayoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KeyboardLayoutJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KeyboardLayoutJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KeyboardLayoutJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KeyboardLayoutJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KeyboardLayoutJDialog dialog = new KeyboardLayoutJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSaveLayout;
    private javax.swing.JComboBox<String> jComboBoxKeyboardLayout;
    private javax.swing.JLabel jLabelLayout;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public String getSelectedKeyboardLayout() {
        return this.selectedKeyboardLayout;
    }
}
