#!/bin/bash
#This file should be place in /etc/pm/sleep.d/
USER=`who | grep ':0' | grep -o '^\w*' | head -n1`
case $1 in
    hibernate)
        #echo "Nothing to do"
    ;;
    suspend)
        #echo "Nothing to do"
    ;;
    thaw)	
        sudo -u $USER "/opt/LogiGSK/LogiGSK" restart
    ;;
    resume)
        sudo -u $USER "/opt/LogiGSK/LogiGSK" restart
    ;;
    *)  #echo "Somebody is calling me totally wrong."
    ;;
esac
